// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo-twelve/internal/handler"
	"demo-twelve/internal/repository"
	"demo-twelve/internal/service"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeTaskHandler() (*handler.TaskHandler, error) {
	db, err := InitDB()
	if err != nil {
		return nil, err
	}
	taskRepository := repository.NewTaskRepository(db)
	taskService := service.NewTaskService(taskRepository)
	client := service.NewDatadogClient()
	taskHandler := handler.NewTaskHandler(taskService, client)
	return taskHandler, nil
}

// wire.go:

// Proveedor de la base de datos (DB)
func InitDB() (*gorm.DB, error) {
	dsn := "admin:SoyAdmin12@tcp(dev-demo.ceccfhe316xj.us-east-1.rds.amazonaws.com:3306)/tasks?charset=utf8mb4&parseTime=True&loc=Local"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		return nil, err
	}

	return db, nil
}
